/*******************************************************************************
 * File Name: project.h  
 * PSoC Creator 2.1 Component Pack 4
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2011, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/
#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <FR_HBridge.h>
#include <PWM_clk.h>
#include <FR_H2.h>
#include <FR_H2_aliases.h>
#include <FR_H.h>
#include <FR_H_aliases.h>
#include <LCD.h>
#include <BR_HBridge.h>
#include <BR_H2.h>
#include <BR_H2_aliases.h>
#include <BR_H.h>
#include <BR_H_aliases.h>
#include <FL_HBridge.h>
#include <FL_H2.h>
#include <FL_H2_aliases.h>
#include <FL_H.h>
#include <FL_H_aliases.h>
#include <BL_HBridge.h>
#include <timer_clock_1.h>
#include <BL_H2.h>
#include <BL_H2_aliases.h>
#include <BL_H.h>
#include <BL_H_aliases.h>
#include <PixyPan.h>
#include <PixyPan_aliases.h>
#include <Pan_int.h>
#include <PixyTilt.h>
#include <PixyTilt_aliases.h>
#include <TiltTime.h>
#include <Pan_Reset.h>
#include <timer_clock.h>
#include <PanTime.h>
#include <pan_reset_clk.h>
#include <Tilt_int.h>
#include <Tilt_Reset.h>
#include <tilt_reset_clk.h>
#include <Clk_int.h>
#include <Gyro_Pin.h>
#include <Gyro_Pin_aliases.h>
#include <ADC.h>
#include <Analog_int.h>
#include <Pixy_int.h>
#include <Clock_1.h>
#include <Pixy_UART.h>
#include <LCD_LCDPort.h>
#include <LCD_LCDPort_aliases.h>
#include <ADC_theACLK.h>
#include <ADC_Ext_CP_Clk.h>
#include <ADC_AMux.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <PSoC3_8051.h>

/*[]*/
